### ISSUE TITLE
Add instructions to deploy controller

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/bumblebee#42]
How does one deploy the CRD and controller before even writing a Transformation ?

**Comment by tzununbekov** [comment]
Manifests in [./config](https://github.com/triggermesh/bumblebee/tree/master/config) directory are ko-appliable. Manifests with images built by our CI currently stored in config repo only. If we want to have ready-to-deploy manifests here we need to change CI pipelines.

**Comment by sebgoa** [comment]
so a simple `ko apply -f ./config` does the trick of installing the CRD and deploying the controller ?

**Comment by tzununbekov** [comment]
correct
